// AUTO-GENERATED by scripts/generate-clubs.ts – do not edit manually.
// Re-run with: npm run generate:clubs (once per season)

export interface Club {
  name: string      // "FC Bayern München"
  shortName: string // "FC Bayern"
  iconUrl: string   // icon URL from OpenLigaDB
  league: 1 | 2 | 3
}

export const CLUBS: Club[] = [
  { name: "1. FC Heidenheim 1846", shortName: "Heidenheim", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/1._FC_Heidenheim_1846.svg/830px-1._FC_Heidenheim_1846.svg.png", league: 1 },
  { name: "1. FC Kaiserslautern", shortName: "Kaiserslautern", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Logo_1_FC_Kaiserslautern.svg", league: 2 },
  { name: "1. FC Köln", shortName: "Köln", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/1._FC_Koeln_Logo_2014–.svg/296px-1._FC_Koeln_Logo_2014–.svg.png", league: 1 },
  { name: "1. FC Magdeburg", shortName: "Magdeburg", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/1._FC_Magdeburg.svg/210px-1._FC_Magdeburg.svg.png", league: 2 },
  { name: "1. FC Nürnberg", shortName: "Nürnberg", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/1._FC_Nürnberg_logo.svg", league: 2 },
  { name: "1. FC Saarbrücken", shortName: "Saarbrücken", iconUrl: "http://upload.wikimedia.org/wikipedia/de/thumb/f/ff/1._FC_Saarbr%C3%BCcken.svg/150px-1._FC_Saarbr%C3%BCcken.svg.png", league: 3 },
  { name: "1. FC Schweinfurt 05", shortName: "1. FC Schweinfurt 05", iconUrl: "https://upload.wikimedia.org/wikipedia/de/thumb/7/7c/1._FC_Schweinfurt_05.svg/534px-1._FC_Schweinfurt_05.svg.png", league: 3 },
  { name: "1. FC Union Berlin", shortName: "Union Berlin", iconUrl: "https://assets.dfb.de/uploads/000/018/232/small_union-Berlin.jpg", league: 1 },
  { name: "1. FSV Mainz 05", shortName: "Mainz", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Logo_Mainz_05.svg/1200px-Logo_Mainz_05.svg.png", league: 1 },
  { name: "Alemannia Aachen", shortName: "Aachen", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Alemannia_Aachen_2010.svg", league: 3 },
  { name: "Bayer 04 Leverkusen", shortName: "Leverkusen", iconUrl: "https://www.bundesliga-reisefuehrer.de/sites/default/files/B04_Standard_Logo_RGB.png", league: 1 },
  { name: "Borussia Dortmund", shortName: "Dortmund", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/560px-Borussia_Dortmund_logo.svg.png", league: 1 },
  { name: "Borussia Mönchengladbach", shortName: "Gladbach", iconUrl: "https://i.imgur.com/KSIk0Eu.png", league: 1 },
  { name: "DSC Arminia Bielefeld", shortName: "Bielefeld", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Logo_mit_Rand.png", league: 2 },
  { name: "Dynamo Dresden", shortName: "Dresden", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Logo_SG_Dynamo_Dresden_neu.svg/284px-Logo_SG_Dynamo_Dresden_neu.svg.png", league: 2 },
  { name: "Eintracht Braunschweig", shortName: "Braunschweig", iconUrl: "https://upload.wikimedia.org/wikipedia/de/4/45/Logo_Eintracht_Braunschweig.svg", league: 2 },
  { name: "Eintracht Frankfurt", shortName: "Frankfurt", iconUrl: "https://i.imgur.com/X8NFkOb.png", league: 1 },
  { name: "Energie Cottbus", shortName: "Cottbus", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/Logo_Energie_Cottbus.svg", league: 3 },
  { name: "Erzgebirge Aue", shortName: "Aue", iconUrl: "https://upload.wikimedia.org/wikipedia/de/thumb/1/13/Fc_erzgebirge_aue.svg/243px-Fc_erzgebirge_aue.svg.png", league: 3 },
  { name: "FC Augsburg", shortName: "Augsburg", iconUrl: "https://i.imgur.com/sdE62e2.png", league: 1 },
  { name: "FC Bayern München", shortName: "Bayern", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg", league: 1 },
  { name: "FC Ingolstadt 04", shortName: "Ingolstadt", iconUrl: "https://upload.wikimedia.org/wikipedia/de/thumb/5/55/FC-Ingolstadt_logo.svg/125px-FC-Ingolstadt_logo.svg.png", league: 3 },
  { name: "FC Schalke 04", shortName: "Schalke", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/9/97/FC_Schalke_04_Logo.png", league: 2 },
  { name: "FC St. Pauli", shortName: "St. Pauli", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Fc_st_pauli_logo.svg", league: 1 },
  { name: "Fortuna Düsseldorf", shortName: "Düsseldorf", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Fortuna_D%C3%BCsseldorf.svg/150px-Fortuna_D%C3%BCsseldorf.svg.png", league: 2 },
  { name: "Hamburger SV", shortName: "HSV", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Hamburger_SV_logo.svg", league: 1 },
  { name: "Hannover 96", shortName: "Hannover", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Hannover_96_Logo.svg", league: 2 },
  { name: "Hansa Rostock", shortName: "Rostock", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/F.C._Hansa_Rostock_Logo.svg/240px-F.C._Hansa_Rostock_Logo.svg.png", league: 3 },
  { name: "Hertha BSC", shortName: "Hertha", iconUrl: "https://i.imgur.com/apFwbYZ.png", league: 2 },
  { name: "Holstein Kiel", shortName: "Kiel", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Holstein_Kiel_Logo.svg/300px-Holstein_Kiel_Logo.svg.png", league: 2 },
  { name: "Jahn Regensburg", shortName: "Regensburg", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Jahn_Regensburg_logo2014.svg/204px-Jahn_Regensburg_logo2014.svg.png", league: 3 },
  { name: "Karlsruher SC", shortName: "Karlsruhe", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Karlsruher_SC_Logo_2.svg", league: 2 },
  { name: "MSV Duisburg", shortName: "Duisburg", iconUrl: "https://upload.wikimedia.org/wikipedia/en/c/c8/Msv_duisburg%28new%29.svg", league: 3 },
  { name: "Preußen Münster", shortName: "Münster", iconUrl: "https://upload.wikimedia.org/wikipedia/de/7/7e/SC_Preussen_Muenster_Logo_2018.svg", league: 2 },
  { name: "RB Leipzig", shortName: "Leipzig", iconUrl: "https://i.imgur.com/Rpwsjz1.png", league: 1 },
  { name: "Rot-Weiss Essen", shortName: "Rot-Weiss Essen", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Rot-Weiss_Essen.png", league: 3 },
  { name: "SC Freiburg", shortName: "Freiburg", iconUrl: "https://i.imgur.com/r3mvi0h.png", league: 1 },
  { name: "SC Paderborn 07", shortName: "Paderborn", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/SC_Paderborn_07_Logo.svg", league: 2 },
  { name: "SC Verl", shortName: "Verl", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/SC_Verl_Logo.svg/211px-SC_Verl_Logo.svg.png", league: 3 },
  { name: "SpVgg Greuther Fürth", shortName: "Fürth", iconUrl: "https://i.imgur.com/pwuVbKr.png", league: 2 },
  { name: "SSV Ulm 1846", shortName: "SSV Ulm 1846", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/SSV_Ulm_1846.svg/150px-SSV_Ulm_1846.svg.png", league: 3 },
  { name: "SV 07 Elversberg", shortName: "Elversberg", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/SV_Elversberg_Logo_2021.svg/150px-SV_Elversberg_Logo_2021.svg.png", league: 2 },
  { name: "SV Darmstadt 98", shortName: "Darmstadt", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e5/SV_Darmstadt_98_Logo.svg", league: 2 },
  { name: "SV Waldhof Mannheim", shortName: "Mannheim", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Svwaldhof.svg/150px-Svwaldhof.svg.png", league: 3 },
  { name: "SV Wehen Wiesbaden", shortName: "Wiesbaden", iconUrl: "https://upload.wikimedia.org/wikipedia/de/thumb/3/3d/Logo_SV_Wehen_Wiesbaden.svg/240px-Logo_SV_Wehen_Wiesbaden.svg.png", league: 3 },
  { name: "SV Werder Bremen", shortName: "Bremen", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SV-Werder-Bremen-Logo.svg/681px-SV-Werder-Bremen-Logo.svg.png", league: 1 },
  { name: "TSG 1899 Hoffenheim II", shortName: "TSG 1899 Hoffenheim II", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Logo_TSG_Hoffenheim.svg/150px-Logo_TSG_Hoffenheim.svg.png", league: 3 },
  { name: "TSG Hoffenheim", shortName: "Hoffenheim", iconUrl: "https://i.imgur.com/gF0PfEl.png", league: 1 },
  { name: "TSV 1860 München", shortName: "1860 München", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/TSV_1860_M%C3%BCnchen.svg/192px-TSV_1860_M%C3%BCnchen.svg.png", league: 3 },
  { name: "TSV Havelse", shortName: "TSV Havelse", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/TSV_Havelse_logo.svg/120px-TSV_Havelse_logo.svg.png", league: 3 },
  { name: "VfB Stuttgart", shortName: "Stuttgart", iconUrl: "https://i.imgur.com/v0tkpNx.png", league: 1 },
  { name: "VfB Stuttgart II", shortName: "Stuttgart II", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/221px-VfB_Stuttgart_1893_Logo.svg.png", league: 3 },
  { name: "VfL Bochum", shortName: "Bochum", iconUrl: "https://i.imgur.com/5jy3Gfr.png", league: 2 },
  { name: "VfL Osnabrück", shortName: "Osnabrück", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/VfL_Osnabrueck_Logo_2021%E2%80%93.svg/240px-VfL_Osnabrueck_Logo_2021%E2%80%93.svg.png", league: 3 },
  { name: "VfL Wolfsburg", shortName: "Wolfsburg", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Logo-VfL-Wolfsburg.svg/316px-Logo-VfL-Wolfsburg.svg.png", league: 1 },
  { name: "Viktoria Köln", shortName: "Viktoria Köln", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/FC_Viktoria_K%C3%B6ln_1904_Logo.svg/1200px-FC_Viktoria_K%C3%B6ln_1904_Logo.svg.png", league: 3 },
]

export function getClubByName(name: string): Club | undefined {
  return CLUBS.find((c) => c.name === name)
}
