'use server'

import { writeFileSync } from 'fs'
import { join } from 'path'
import { getSession } from '@/lib/auth'
import { getLocalClubIconPath, normalizeIconUrl } from '@/lib/club-icon-path'

const BASE_URL = 'https://api.openligadb.de'

interface ApiTeam {
  teamId: number
  teamName: string
  shortName: string
  teamIconUrl: string
}

async function requireAdmin() {
  const session = await getSession()
  if (!session || session.user.role !== 'ADMIN') throw new Error('Nicht autorisiert')
}

export async function regenerateClubs(year: string): Promise<{ count?: number; error?: string }> {
  await requireAdmin()

  let bl1: ApiTeam[], bl2: ApiTeam[], bl3: ApiTeam[]
  try {
    ;[bl1, bl2, bl3] = await Promise.all(
      ['bl1', 'bl2', 'bl3'].map(async (league) => {
        const res = await fetch(`${BASE_URL}/getavailableteams/${league}/${year}`, {
          cache: 'no-store',
        })
        if (!res.ok) throw new Error(`OpenLigaDB ${league}: HTTP ${res.status}`)
        return res.json() as Promise<ApiTeam[]>
      }),
    )
  } catch (e) {
    return { error: `OpenLigaDB-Fehler: ${e instanceof Error ? e.message : String(e)}` }
  }

  type League = 1 | 2 | 3
  const all: Array<{ name: string; shortName: string; iconUrl: string; iconSourceUrl: string; league: League }> = [
    ...bl1.map((t) => {
      const iconSourceUrl = normalizeIconUrl(t.teamIconUrl)
      return { name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: getLocalClubIconPath(t.teamName, iconSourceUrl), iconSourceUrl, league: 1 as League }
    }),
    ...bl2.map((t) => {
      const iconSourceUrl = normalizeIconUrl(t.teamIconUrl)
      return { name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: getLocalClubIconPath(t.teamName, iconSourceUrl), iconSourceUrl, league: 2 as League }
    }),
    ...bl3.map((t) => {
      const iconSourceUrl = normalizeIconUrl(t.teamIconUrl)
      return { name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: getLocalClubIconPath(t.teamName, iconSourceUrl), iconSourceUrl, league: 3 as League }
    }),
  ]

  const seen = new Set<string>()
  const clubs = all
    .filter((c) => {
      if (seen.has(c.name)) return false
      seen.add(c.name)
      return true
    })
    .sort((a, b) => a.name.localeCompare(b.name, 'de'))

  const lines = clubs.map(
    (c) =>
      `  { name: ${JSON.stringify(c.name)}, shortName: ${JSON.stringify(c.shortName)}, iconUrl: ${JSON.stringify(c.iconUrl)}, iconSourceUrl: ${JSON.stringify(c.iconSourceUrl)}, league: ${c.league} },`,
  )

  const content = `// AUTO-GENERATED by scripts/generate-clubs.ts – do not edit manually.
// Re-run with: npm run generate:clubs (once per season)

export interface Club {
  name: string      // "FC Bayern München"
  shortName: string // "FC Bayern"
  iconUrl: string   // local public path, e.g. "/club-icons/fc-bayern-muenchen.svg"
  iconSourceUrl: string // original remote icon URL
  league: 1 | 2 | 3
}

export const CLUBS: Club[] = [
${lines.join('\n')}
]

export function getClubByName(name: string): Club | undefined {
  return CLUBS.find((c) => c.name === name)
}
`

  try {
    writeFileSync(join(process.cwd(), 'src', 'lib', 'clubs.ts'), content, 'utf-8')
  } catch (e) {
    return { error: `Datei konnte nicht geschrieben werden: ${e instanceof Error ? e.message : String(e)}` }
  }

  return { count: clubs.length }
}
