/**
 * Fetches teams from OpenLigaDB for BL1, BL2, BL3 (2024 season)
 * and writes a static src/lib/clubs.ts file.
 *
 * Usage: npm run generate:clubs
 */

import { writeFileSync } from 'fs'
import { join } from 'path'

const BASE = 'https://api.openligadb.de'
const YEAR = '2024'

interface ApiTeam {
  teamId: number
  teamName: string
  shortName: string
  teamIconUrl: string
}

async function fetchTeams(league: string): Promise<ApiTeam[]> {
  const res = await fetch(`${BASE}/getavailableteams/${league}/${YEAR}`)
  if (!res.ok) throw new Error(`Failed to fetch ${league}: ${res.status}`)
  return res.json()
}

async function main() {
  console.log('Fetching teams from OpenLigaDB…')

  const [bl1, bl2, bl3] = await Promise.all([
    fetchTeams('bl1'),
    fetchTeams('bl2'),
    fetchTeams('bl3'),
  ])

  console.log(`BL1: ${bl1.length} teams, BL2: ${bl2.length} teams, BL3: ${bl3.length} teams`)

  type League = 1 | 2 | 3

  const allClubs: Array<{
    name: string
    shortName: string
    iconUrl: string
    league: League
  }> = [
    ...bl1.map((t) => ({ name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: t.teamIconUrl, league: 1 as League })),
    ...bl2.map((t) => ({ name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: t.teamIconUrl, league: 2 as League })),
    ...bl3.map((t) => ({ name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: t.teamIconUrl, league: 3 as League })),
  ]

  // Deduplicate by name (a team might appear in multiple leagues if relegated/promoted data overlaps)
  const seen = new Set<string>()
  const deduped = allClubs.filter((c) => {
    if (seen.has(c.name)) return false
    seen.add(c.name)
    return true
  })

  // Sort alphabetically
  deduped.sort((a, b) => a.name.localeCompare(b.name, 'de'))

  const lines = deduped.map(
    (c) =>
      `  { name: ${JSON.stringify(c.name)}, shortName: ${JSON.stringify(c.shortName)}, iconUrl: ${JSON.stringify(c.iconUrl)}, league: ${c.league} },`,
  )

  const output = `// AUTO-GENERATED by scripts/generate-clubs.ts – do not edit manually.
// Re-run with: npm run generate:clubs (once per season)

export interface Club {
  name: string      // "FC Bayern München"
  shortName: string // "FC Bayern"
  iconUrl: string   // icon URL from OpenLigaDB
  league: 1 | 2 | 3
}

export const CLUBS: Club[] = [
${lines.join('\n')}
]

export function getClubByName(name: string): Club | undefined {
  return CLUBS.find((c) => c.name === name)
}
`

  const outPath = join(process.cwd(), 'src', 'lib', 'clubs.ts')
  writeFileSync(outPath, output, 'utf-8')
  console.log(`Written ${deduped.length} clubs → ${outPath}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
