import { writeFile } from 'node:fs/promises'
import { join } from 'path'
import { z } from 'zod'
import { getLocalClubIconPath, normalizeIconUrl } from '../src/lib/club-icon-path'

const BASE = 'https://api.openligadb.de'
const year = process.argv[2]
if (!year || !/^\d{4}$/.test(year)) {
  throw new Error('Usage: npm run generate:clubs -- <season-start-year>')
}

interface ApiTeam {
  teamId: number
  teamName: string
  shortName: string
  teamIconUrl: string
}

const apiTeamSchema = z.object({
  teamId: z.number().int().positive(),
  teamName: z.string().min(1).max(255),
  shortName: z.string().max(255),
  teamIconUrl: z.string().url().max(2_048),
})

async function fetchTeams(league: string): Promise<ApiTeam[]> {
  const res = await fetch(`${BASE}/getavailableteams/${league}/${year}`, {
    signal: AbortSignal.timeout(12_000),
  })
  if (!res.ok) throw new Error(`Failed to fetch ${league}: ${res.status}`)
  return z.array(apiTeamSchema).max(30).parse(await res.json())
}

async function main() {
  console.log('Fetching teams from OpenLigaDB…')

  const [bl1, bl2, bl3] = await Promise.all([
    fetchTeams('bl1'),
    fetchTeams('bl2'),
    fetchTeams('bl3'),
  ])

  console.log(`BL1: ${bl1.length} teams, BL2: ${bl2.length} teams, BL3: ${bl3.length} teams`)

  type League = 1 | 2 | 3

  const allClubs: Array<{
    name: string
    shortName: string
    iconUrl: string
    iconSourceUrl: string
    league: League
  }> = [
    ...bl1.map((t) => {
      const iconSourceUrl = normalizeIconUrl(t.teamIconUrl)
      return { name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: getLocalClubIconPath(t.teamName, iconSourceUrl), iconSourceUrl, league: 1 as League }
    }),
    ...bl2.map((t) => {
      const iconSourceUrl = normalizeIconUrl(t.teamIconUrl)
      return { name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: getLocalClubIconPath(t.teamName, iconSourceUrl), iconSourceUrl, league: 2 as League }
    }),
    ...bl3.map((t) => {
      const iconSourceUrl = normalizeIconUrl(t.teamIconUrl)
      return { name: t.teamName, shortName: t.shortName || t.teamName, iconUrl: getLocalClubIconPath(t.teamName, iconSourceUrl), iconSourceUrl, league: 3 as League }
    }),
  ]

  // OpenLigaDB can list a promoted or relegated club in overlapping league
  // datasets. The application needs one canonical entry per club name.
  const seen = new Set<string>()
  const deduped = allClubs.filter((c) => {
    if (seen.has(c.name)) return false
    seen.add(c.name)
    return true
  })

  deduped.sort((a, b) => a.name.localeCompare(b.name, 'de'))

  const lines = deduped.map(
    (c) =>
      `  { name: ${JSON.stringify(c.name)}, shortName: ${JSON.stringify(c.shortName)}, iconUrl: ${JSON.stringify(c.iconUrl)}, iconSourceUrl: ${JSON.stringify(c.iconSourceUrl)}, league: ${c.league} },`,
  )

  const output = `// AUTO-GENERATED by scripts/generate-clubs.ts – do not edit manually.
// Re-run with: npm run generate:clubs -- <season-start-year>

export interface Club {
  name: string
  shortName: string
  iconUrl: string
  iconSourceUrl: string
  league: 1 | 2 | 3
}

export const CLUBS: Club[] = [
${lines.join('\n')}
]

export function getClubByName(name: string): Club | undefined {
  return CLUBS.find((c) => c.name === name)
}
`

  const outPath = join(process.cwd(), 'src', 'lib', 'clubs.ts')
  await writeFile(outPath, output, 'utf-8')
  console.log(`Written ${deduped.length} clubs → ${outPath}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
