import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

function stripDiacritics(value) {
  return value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
}

function normalizeIconUrl(url) {
  return url.replace(/^http:\/\//i, 'https://')
}

function slugifyClubName(name) {
  return stripDiacritics(name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function inferIconExtension(url) {
  const pathname = new URL(normalizeIconUrl(url)).pathname.toLowerCase()
  const match = pathname.match(/\.([a-z0-9]+)$/)
  const ext = match?.[1] ?? 'png'

  if (ext === 'jpeg') return 'jpg'
  if (['svg', 'png', 'jpg', 'webp'].includes(ext)) return ext
  return 'png'
}

function getLocalClubIconPath(name, sourceUrl) {
  return `/club-icons/${slugifyClubName(name)}.${inferIconExtension(sourceUrl)}`
}

function readClubs() {
  const source = readFileSync(join(process.cwd(), 'src', 'lib', 'clubs.ts'), 'utf8')
  const match = source.match(/export const CLUBS: Club\[\] = \[(?<body>[\s\S]*?)\n\]/)

  if (!match?.groups?.body) {
    throw new Error('CLUBS array not found in src/lib/clubs.ts')
  }

  return Function(`return [${match.groups.body}]`)()
}

const clubs = readClubs().map((club) => {
  const iconSourceUrl = normalizeIconUrl(club.iconSourceUrl ?? club.iconUrl)
  return {
    ...club,
    iconUrl: getLocalClubIconPath(club.name, iconSourceUrl),
    iconSourceUrl,
  }
})

const content = `// AUTO-GENERATED by scripts/generate-clubs.ts – do not edit manually.
// Re-run with: npm run generate:clubs -- <season-start-year>

export interface Club {
  name: string      // "FC Bayern München"
  shortName: string // "FC Bayern"
  iconUrl: string   // local public path, e.g. "/club-icons/fc-bayern-muenchen.svg"
  iconSourceUrl: string // original remote icon URL
  league: 1 | 2 | 3
}

export const CLUBS: Club[] = [
${clubs.map((c) => `  { name: ${JSON.stringify(c.name)}, shortName: ${JSON.stringify(c.shortName)}, iconUrl: ${JSON.stringify(c.iconUrl)}, iconSourceUrl: ${JSON.stringify(c.iconSourceUrl)}, league: ${c.league} },`).join('\n')}
]

export function getClubByName(name: string): Club | undefined {
  return CLUBS.find((c) => c.name === name)
}
`

writeFileSync(join(process.cwd(), 'src', 'lib', 'clubs.ts'), content, 'utf8')
console.log(`Localized ${clubs.length} club icons in src/lib/clubs.ts`)
